function(enable_sanitizers target_name)
    if(CMAKE_BUILD_TYPE STREQUAL "Debug" AND CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
        option(ENABLE_ASAN "Enable AddressSanitizer" OFF)
        option(ENABLE_UBSAN "Enable UndefinedBehaviorSanitizer" OFF)

        set(SANITIZERS "")
        if(ENABLE_ASAN)
            list(APPEND SANITIZERS "address")
        endif()
        if(ENABLE_UBSAN)
            list(APPEND SANITIZERS "undefined")
        endif()

        if(SANITIZERS)
            string(JOIN "," SANITIZER_LIST ${SANITIZERS})
            target_compile_options(${target_name} PRIVATE -fsanitize=${SANITIZER_LIST} -fno-omit-frame-pointer)
            target_link_options(${target_name} PRIVATE -fsanitize=${SANITIZER_LIST})
        endif()
    endif()
endfunction()
